"""tag category

Revision ID: 06a3c151896c
Revises: 5e8649c658db
Create Date: 2021-04-02 11:54:41.521465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a3c151896c'
down_revision = '5e8649c658db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
