"""post_tag index

Revision ID: 4026325ad89e
Revises: 8e9e3a1e85d6
Create Date: 2021-04-02 15:14:00.308907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4026325ad89e'
down_revision = '8e9e3a1e85d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_tag_post_id'), 'post_tag', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_tag_tag_id'), 'post_tag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_tag_tag_id'), table_name='post_tag')
    op.drop_index(op.f('ix_post_tag_post_id'), table_name='post_tag')
    # ### end Alembic commands ###
