"""delete post_category

Revision ID: 8e9e3a1e85d6
Revises: adc2f87f543a
Create Date: 2021-04-02 14:35:33.033222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e9e3a1e85d6'
down_revision = 'adc2f87f543a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_category')
    op.add_column('post', sa.Column('category_id', sa.BigInteger(), nullable=True, comment='分类id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'category_id')
    op.create_table('post_category',
    sa.Column('post_cid', mysql.BIGINT(), autoincrement=True, nullable=False, comment='关系id'),
    sa.Column('post_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='文章id'),
    sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='分类id'),
    sa.PrimaryKeyConstraint('post_cid'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
