"""tag category

Revision ID: adc2f87f543a
Revises: 06a3c151896c
Create Date: 2021-04-02 11:56:24.490422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc2f87f543a'
down_revision = '06a3c151896c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='分类id'),
    sa.Column('name', sa.String(length=25), nullable=False, comment='分类名'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_category_created_at'), 'category', ['created_at'], unique=False)
    op.create_table('tag',
    sa.Column('tag_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='标签id'),
    sa.Column('name', sa.String(length=25), nullable=False, comment='标签名'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tag_created_at'), 'tag', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_created_at'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_category_created_at'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
